spring:
  application:
    name: treasure-hunt-registration

  # Default to production profile for security
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:production}

  # Database Configuration (H2 for development only - production uses PostgreSQL)
  datasource:
    url: jdbc:h2:mem:treasure_hunt_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        jdbc:
          time_zone: UTC

  # H2 Console (for development only)
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:false}
      path: /h2-console
  
  # Thymeleaf Configuration
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
  
  # Mail Configuration - DEVELOPMENT ONLY (Production uses environment variables)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:development@example.com}
    password: ${MAIL_PASSWORD:CHANGE_ME}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          ssl:
            trust: smtp.gmail.com
  
  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 50MB  # Increased to support video uploads
      max-request-size: 60MB  # Increased to support video uploads
      enabled: true
      file-size-threshold: 2KB
      location: ${java.io.tmpdir}

# Custom Application Properties
app:
  file-storage:
    upload-dir: uploads/documents
    image-dir: uploads/images
    max-photo-size: 2097152  # 2MB in bytes for registration photos
    max-document-size: 5242880  # 5MB in bytes for documents
    max-image-size: 5242880  # 5MB in bytes for admin image uploads
    max-video-size: 52428800  # 50MB in bytes for admin video uploads
    allowed-photo-types: image/jpeg,image/jpg,image/png
    allowed-document-types: application/pdf,image/jpeg,image/jpg
  
  email:
    from: ${MAIL_FROM_ADDRESS:development@example.com}
    support: ${MAIL_SUPPORT_ADDRESS:support@example.com}
    company-name: ${COMPANY_NAME:Treasure Hunt Adventures}
    mock:
      enabled: false  # Disabled - Use real Gmail SMTP

  security:
    admin:
      username: ${ADMIN_USERNAME:CHANGE_ME}
      password: ${ADMIN_PASSWORD:CHANGE_ME}

# Logging Configuration
logging:
  level:
    com.treasurehunt: INFO
    org.springframework.security: WARN
    org.springframework.mail: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/treasure-hunt.log

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
  error:
    include-message: ${INCLUDE_ERROR_MESSAGE:never}
    include-binding-errors: ${INCLUDE_BINDING_ERRORS:never}
    include-stacktrace: never
    include-exception: false
  shutdown: graceful
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Graceful Shutdown Configuration
spring.lifecycle.timeout-per-shutdown-phase: 30s
