name: Deploy to Azure App Service

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: treasure-hunt-adventures    # Set this to your Azure Web App name
  JAVA_VERSION: '17'                             # Set this to the Java version to use
  DISTRIBUTION: 'temurin'                        # Set this to the Java distribution

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 🔄 Checkout code
      uses: actions/checkout@v4
      
    - name: ☕ Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: ${{ env.DISTRIBUTION }}
        
    - name: 📦 Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: 🧪 Run tests
      run: mvn clean test
      
    - name: 🔨 Build application
      run: mvn clean package -DskipTests -Pprod
      
    - name: 📋 Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: 📥 Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: java-app
        
    - name: 🚀 Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'Production'
        package: '*.jar'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        
    - name: ✅ Deployment completed
      run: |
        echo "🎉 Application deployed successfully!"
        echo "🌐 Application URL: ${{ steps.deploy-to-webapp.outputs.webapp-url }}"
